# Docker Compose Base
version : '3.5'
services:
        live-web:
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                image: open-vote-live-web